### ISSUE TITLE
Regarding resolution of ZED camera

### ISSUE THREAD

**Issue by omnajain** [tobybreckon/zed-opencv-native-python#2]
Unexpected error while using this command:
python ./zed-stereo.py --serial 000022406 --camera_to_use 1

Error - selected camera # 1  : resolution does not match a known ZED configuration profile.

**Comment by tobybreckon** [comment]
Interesting, can you please disconnect/connect the ZED camera to your (linux) PC again and send me the output of the following shell commands:
```
ls /dev/video*
```
and also:
```
dmesg | tail -20
```
Is a ```zed-cam-sn-22406.conf``` file (or similar) produced when you run the python script ?
(if so please also attach to reply)

This error is normally caused by either the wrong camera ID being selected or alternatively the machine not having internet access to download the calibration file via the ZED calibration web service.

**Comment by omnajain** [comment]
Hello sir,
I had tried to connect my ZED Camera with Linux, camera is working without
using serial number but showing warning:

Warning - no serial number or config file specified.

I had used these commands and had attached the screenshot of the result
obtained.

ls /dev/video* and dmesg | tail -20

**Comment by tobybreckon** [comment]
No screenshot attached.

Please run commands and copy/paste output into this thread.

**Comment by omnajain** [comment]
Sir I had attached the output of terminal.


spcom@dell-OptiPlex-3040:~/Desktop/omna/zed-opencv-native-python$ python3
./zed-stereo.py
Warning - no serial number or config file specified.


ZED left/right resolution:  672  x  376
ZED mode:  VGA

Keyboard Controls:
space - change camera mode
f - toggle disparity full-screen mode
c - toggle disparity false colour mapping
t - toggle display centre target cross-hairs and depth
h - toggle horizontal side by side [left image | disparity]
v - toggle vertical side by side [left image | disparity]
i - toggle disparity in-filling via interpolation
x - exit

^CTraceback (most recent call last):
  File "./zed-stereo.py", line 386, in <module>
    key = cv2.waitKey(max(2, 40 - int(math.ceil(stop_t)))) & 0xFF;
KeyboardInterrupt
spcom@dell-OptiPlex-3040:~/Desktop/omna/zed-opencv-native-python$ ls
/dev/video*
/dev/video0
spcom@dell-OptiPlex-3040:~/Desktop/omna/zed-opencv-native-python$ ls
camera_stream.py  LICENSE  __pycache__  README.md  SN22406.conf  test.py
 utils.py  zed_calibration.py  zed-cam-sn-000022406.conf
 zed-cam-sn-1010.conf  zed-stereo.py
spcom@dell-OptiPlex-3040:~/Desktop/omna/zed-opencv-native-python$ dmesg |
tail -20
[   35.257579] Bluetooth: BNEP filters: protocol multicast
[   35.257581] Bluetooth: BNEP socket layer initialized
[   63.767360] FS-Cache: Loaded
[   63.974226] FS-Cache: Netfs 'nfs' registered for caching
[   64.022423] NFS: Registering the id_resolver key type
[   64.022429] Key type id_resolver registered
[   64.022434] Key type id_legacy registered
[  306.840577] usb 1-10: new high-speed USB device number 4 using xhci_hcd
[  306.969536] usb 1-10: New USB device found, idVendor=2b03, idProduct=f582
[  306.969545] usb 1-10: New USB device strings: Mfr=1, Product=2,
SerialNumber=0
[  306.969550] usb 1-10: Product: ZED
[  306.969555] usb 1-10: Manufacturer: Technologies, Inc.
[  307.004567] media: Linux media interface: v0.10
[  307.014355] Linux video capture interface: v2.00
[  307.056528] uvcvideo: Found UVC 1.10 device ZED (2b03:f582)
[  307.057877] input: ZED as
/devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.0/input/input15
[  307.058161] usbcore: registered new interface driver uvcvideo
[  307.058167] USB Video Class driver (1.1.1)
[  319.034076] audit: type=1400 audit(1576819426.743:45): apparmor="DENIED"
operation="open" profile="/usr/sbin/cupsd" name="/etc/ldap/ldap.conf"
pid=722 comm="cupsd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 2281.133126] audit: type=1400 audit(1576821388.819:46): apparmor="DENIED"
operation="open" profile="/usr/sbin/cupsd" name="/etc/ldap/ldap.conf"
pid=2762 comm="cupsd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

**Comment by tobybreckon** [comment]
Thanks.

Can I confirm which model of ZED camera it is?

Also can you attach the zed-cam-sn-000022406.conf file, please.

**Comment by omnajain** [comment]
It is ZED Stereo camera.
https://www.stereolabs.com/zed/

**Comment by tobybreckon** [comment]
Still waiting on the .conf file ...

**Comment by omnajain** [comment]
I had attached zed-cam-sn-000022406.conf file in the previous email also.
Here I am attaching 3 .conf file.

**Comment by tobybreckon** [comment]
Reply via github.com not email, no config file received.

**Comment by tobybreckon** [comment]
So re-examining this the solution you need is:

`python ./zed-stereo.py --serial 000022406 --camera_to_use 0`

 ... as you only have 1 video device (```/dev/video0```) which are numbered 0 to N under linux, not from 1. 

Your camera has a valid calibration file available - http://calib.stereolabs.com/?SN=22406 which matches the format of the default one -  http://calib.stereolabs.com/?SN=1010
